### ISSUE TITLE
能否下载整个表情包并自动转gif

### ISSUE THREAD

**Issue by qththq** [rroy233/StickerDownloader#5]

**Comment by rroy233** [comment]
这个功能一直都有的。
发送单个表情或表情包链接给bot，点击bot回复中的“下载整套表情包”按钮，bot就会把所有表情转为gif并打包发给你。

**Comment by qththq** [comment]
好的，这bot需要自建吗，之前使用过类似的bot但是功能残缺，被限制了下载，有没有已有的bot推荐下？

**Comment by rroy233** [comment]
可以自建，也可以使用项目官方的demo：https://t.me/stickers_download_bot
官方demo会限制24h内使用次数、表情包批量下载数量等。

**Comment by qththq** [comment]
这是你建的吗？官方的限制多少，好像表情包太多下载不了

**Comment by rroy233** [comment]
是的，用这个仓库的代码部署的。目前表情包批量下载数量限制为80。
如果有更高需求，建议自行部署。

**Comment by qththq** [comment]
好的，非常感谢！

**Comment by qththq** [comment]
ffmpeg这块放哪个文件夹，下载的已编译的可执行文件需要tar.gz格式解压不？
我部署在only v6机器上发表情包链接没反应，另外最后执行run.sh文件时候成功了一次，之后就一直失败了

**Comment by rroy233** [comment]
从github release下载的tar.gz当然需要解压。
解压后找到ffmpeg可执行文件，放在程序目录下的ffmpeg文件夹中，如[readme](https://github.com/rroy233/StickerDownloader?tab=readme-ov-file#%E4%B8%8B%E8%BD%BDffmpeg)中所说的那样。
启动失败请查看日志sys.log中的内容。

**Comment by qththq** [comment]
root/StickerDownloader/ffmpeg/ffmpeg这样吗

**Comment by rroy233** [comment]
是的

**Comment by qththq** [comment]
2024/09/13 04:43:51 [main]config={"General":{"BotToken":"7478576183:AAEm0a-UcfUv3X5bzrovkGeIuSbFs14ZbC0","Language":"zh-hans","WorkerNum":2,"DownloadWorkerNum":3,"AdminUID":6922965976,"UserDailyLimit":50,"ProcessWaitQueueMaxSize":50,"ProcessTimeout":60,"SupportTGSFile":false,"MaxAmountPerReq":300},"cache":{"Enabled":false,"StorageDir":"./storage/cache","MaxDiskUsage":1024,"CacheExpire":86400,"CacheCleanInterval":1800},"Logger":{"Report":false,"ReportUrl":"","ReportQueryKey":""},"Redis":{"Server":"localhost","Port":"6379","TLS":false,"Password":"","DB":0}}
INFO 2024-09-13 04:43:51 [./../../home/runner/work/StickerDownloader/StickerDownloader/languages/language.go:79] Loaded language <en>
INFO 2024-09-13 04:43:51 [./../../home/runner/work/StickerDownloader/StickerDownloader/languages/language.go:79] Loaded language <fr>
INFO 2024-09-13 04:43:51 [./../../home/runner/work/StickerDownloader/StickerDownloader/languages/language.go:79] Loaded language <ru>
INFO 2024-09-13 04:43:51 [./../../home/runner/work/StickerDownloader/StickerDownloader/languages/language.go:79] Loaded language <zh-hans>
INFO 2024-09-13 04:43:51 [./../../home/runner/work/StickerDownloader/StickerDownloader/languages/language.go:79] Loaded language <zh-hant>
2024/09/13 04:43:51 [系统服务][日志监控进程]已确定下一个苏醒时间
FATAL 2024-09-13 16:43:52 [./../../home/runner/work/StickerDownloader/StickerDownloader/db/init.go:33] Redis启动失败: NOAUTH Authentication required.
必须要开Redis吗？配置里不是可以不启动Redis？

**Comment by rroy233** [comment]
![Snipaste_2024-09-13_16-51-17](https://github.com/user-attachments/assets/8fe2ec96-ae46-4fc3-8b5e-4610956ef629)

必须。

**Comment by qththq** [comment]
OK，成功了，超厉害！
有没有更多配置介绍，想关闭除了管理之外的访问，或者分开限制管理和普通用户
  user_daily_limit: 10 # 每日使用次数限制
  process_wait_queue_max_size: 50 # 等待队列最大长度
  process_timeout: 60 # 处理超时时间(s)
  support_tgs_file: false # 是否开启tgs表情支持
  max_amount_per_req: 100 # 下载整套表情包时允许的最大数量
这几个属性是对普通用户的限制吗？管理无限制？

**Comment by qththq** [comment]
怎么查看别人使用记录，如果修改配置的话，是重新运行run.sh吗？怎么停止bot呢

**Comment by qththq** [comment]
怎么查看别人使用记录，如果修改配置的话，是重新运行run.sh吗？怎么停止bot呢

**Comment by rroy233** [comment]
查看日志文件。使用kill结束进程。
